INITIAL_MESSAGE = "WELCOME TO THE RANDOM PASSWORD GENERATOR! PLEASE ANSWER TO OUR QUESTIONS TO GENERATE A RANDOM PASSWORD!"



ABC = 'abcdefghijklmnopqrstuvwxyz'
ABC_LEN = len(ABC)

SPECIAL_CHARS = '!@#$%&?/\|.:;~'
SPECIAL_CHARS_LEN = len(SPECIAL_CHARS)

NUMBERS = '1234567890'
NUMBERS_LEN = len(NUMBERS)

